FROM ubuntu:latest

RUN apt-get update && apt-get upgrade -y
RUN apt-get -y python3 python3-pip install build-essential libssl-dev libffi-dev python3-dev git

WORKDIR /home/elastalert

ADD requirements*.txt ./
RUN pip3 install -r requirements-dev.txt
